### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by berquist** [micb25/libboys#1]
In the [README](https://github.com/micb25/libboys/commit/a0cd7781e4bd3e3e11f3de544cdf5551b584ea24#diff-04c6e90faac2675aa89e2176d2eec7d8), it says this library is licensed under the LGPL, but the [LICENSE file](https://github.com/micb25/libboys/blob/b7abb89791ea945762e5549994819134c1ab8f6b/LICENSE) is for the regular GPL. Can you clarify which one is intended to be used?

**Comment by micb25** [comment]
Hi Eric,

thanks for spotting this. The LGPL is the intended license for libboys as it is stated in the README file and Fortran sources. I updated the LICENSE file accordingly.

Best regards,
Michael
